// Regenerates src/contracts/abi.ts from the Foundry build (run `forge build` in ../contracts first).
import { readFileSync, writeFileSync } from "node:fs";
const OUT = new URL("../../contracts/out/", import.meta.url);
const names = ["BudgetVault", "BudgetVaultFactory", "FeeJar"];
const consts = { BudgetVault: "BUDGET_VAULT_FULL_ABI", BudgetVaultFactory: "BUDGET_VAULT_FACTORY_ABI", FeeJar: "FEE_JAR_ABI" };
let src = "// Generated by scripts/gen-abi.mjs from the Foundry build. Do not edit by hand.\n";
for (const n of names) {
  const abi = JSON.parse(readFileSync(new URL(`${n}.sol/${n}.json`, OUT), "utf8")).abi;
  src += `\nexport const ${consts[n]} = ${JSON.stringify(abi, null, 2)} as const;\n`;
}
writeFileSync(new URL("../src/contracts/abi.ts", import.meta.url), src);
console.log("wrote src/contracts/abi.ts");
